

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.51.51.34:8848
      password: nacos
      username: nacos
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
  redis:
    host: localhost
    port: 6379
    # password: 123456
  shardingsphere:
    datasource:
      ds-0:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/congomall_customer_user?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
        password: 123456
        username: root
