

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.51.51.34:8848

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/congomall_bff?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false

geetest:
  captcha-id: '极验申请免费试用'
  private-key: '同上'
