

server:
  port: 8003
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-user-service
          predicates:
            - Path=/api/customer-user/**
          uri: lb://customer-user-service/api/customer-user/**
    nacos:
      discovery:
        server-addr: 10.51.51.34:8848
