spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.51.51.34:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    password: XERZPMCFAIDMBXNY
    port: 25
    protocol: smtp
    username: congomall@163.com
  redis:
    host: localhost
    port: 6379
    # password: 123456
  shardingsphere:
    datasource:
      ds-0:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/congomall_message?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
