

spring:
  shardingsphere:
    datasource:
      ds-0:
        username: root
        password: root
        jdbc-url: jdbc:mysql://localhost:3306/congomall_message?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
